// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: rbac.proto

package server

import (
	"context"

	"gozero/app/rbac/rpc/internal/logic"
	"gozero/app/rbac/rpc/internal/svc"
	"gozero/app/rbac/rpc/pb"
)

type RbacServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRbacServer
}

func NewRbacServer(svcCtx *svc.ServiceContext) *RbacServer {
	return &RbacServer{
		svcCtx: svcCtx,
	}
}

func (s *RbacServer) Ping(ctx context.Context, in *pb.Request) (*pb.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
